version: "3"
services:
  db:
    container_name: polls_viewer_db
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  django:
    container_name: polls_app
    build:
      context: .
    env_file: .env
    volumes:
      - ./mysite/:/app
    ports:
      - ${POLLS_VIEWER_PORT}:8000
    depends_on:
      - db
